
INSERT INTO [dbo].[Teams]
           ([Name]
           ,[GroupId]
           ,[SportsEventId],
		   [Flag])
     VALUES
           ('Russland',1,1,'flag-ru'),
		   ('Saudi-Arabia',1,1,'flag-sa'),
		   ('Egypt',1,1,'flag-eg'),
		   ('Uruguay',1,1,'flag-uy'),
		   ('Portugal',2,1,'flag-pt'),
		   ('Spania',2,1,'flag-es'),
		   ('Marokko',2,1,'flag-ma'),
		   ('Iran',2,1,'flag-ir'),
		   ('Frankrike',3,1,'flag-fr'),
		   ('Australia',3,1,'flag-au'),
		   ('Peru',3,1,'flag-pe'),
		   ('Danmark',3,1,'flag-dk'),
		   ('Argentina',4,1,'flag-ag'),
		   ('Island',4,1,'flag-is'),
		   ('Kroatia',4,1,'flag-hr'),
		   ('Nigeria',4,1,'flag-ng'),
		   ('Brasil',5,1,'flag-br'),
		   ('Sveits',5,1,'flag-ch'),
		   ('Costa Rica',5,1,'flag-cr'),
		   ('Serbia',5,1,'flag-rs'),
		   ('Tyskland',6,1,'flag-de'),
		   ('Mexico',6,1,'flag-mx'),
		   ('Sverige',6,1,'flag-se'),
		   ('Sør-Korea',6,1,'flag-kr'),
		   ('Belgia',7,1,'flag-be'),
		   ('Panama',7,1,'flag-pa'),
		   ('Tunisia',7,1,'flag-tn'),
		   ('England',7,1,'flag-gb'),
		   ('Polen',8,1,'flag-pl'),
		   ('Senegal',8,1,'flag-sn'),
		   ('Colombia',8,1,'flag-co'),
		   ('Japan',8,1,'flag-jp')
GO
