drop TABLE Leagues
drop TABLE LeagueUsers
drop TABLE ScoreBasis
drop TABLE UserScores
drop TABLE Results
drop TABLE PlayoffBets
DROP TABLE Bets
drop TABLE UserBets
drop TABLE Teams
drop TABLE PlayoffGameDetails
drop TABLE Games
drop TABLE Groups
drop TABLE SportsEvents
