SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TeamGames](
	[TeamId] int NOT NULL FOREIGN KEY REFERENCES Teams(Id),
	[IsHomeTeam] bit NOT NULL,
	[GameId] int NOT NULL FOREIGN KEY REFERENCES Games(Id),
	[Id] [int] IDENTITY(1,1) NOT NULL,
 PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO
