SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [dbo].[UserScores](
	[Score] [int] NOT NULL,
	[PlayoffScore] [int] NULL,
	[SportsEventId] int NOT NULL FOREIGN KEY REFERENCES SportsEvents(Id),
	[UserId] [varchar](255) NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
    [TopScorerScore] [int] NULL,
 CONSTRAINT [PrimaryKey_4929abcf-b3fd-4f3f-85bc-72b7c7b481c4] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO

