SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [dbo].[ScoreBasis](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GameType] [int] NOT NULL,
	[SportsEventId] int NOT NULL,
	[GradeOfMatchType] int NOT NULL,
	[Points] int NOT NULL,
	[IsRunnerUp] bit NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO

