drop TABLE Leagues
drop TABLE LeagueUsers
drop TABLE ScoreBasis
drop TABLE UserScores
drop TABLE Results
drop TABLE PlayoffBets
DROP TABLE Bets
drop TABLE UserBets
drop TABLE TeamGames
drop TABLE Teams
drop TABLE PlayoffGameDetails
drop TABLE Games
drop TABLE Groups
drop TABLE SportsEvents
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SportsEvents](
	[Name] [nvarchar](50) NOT NULL,
	[StartDate] [datetime] NOT NULL,
	[EndDate] [datetime] NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PrimaryKey_041ebfdb-1db0-452f-99d4-946ff6ebf721] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Groups](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](55) NOT NULL,
	[WinnerTeamCode] [varchar](55) NULL,
	[RunnerUpTeamCode] [varchar](55) NULL,
	[ThirdPlaceTeamCode] [varchar](55) NULL,
	[WinnerGameCode] [varchar](55) NULL,
	[RunnerUpGameCode] [varchar](55) NULL,
	[SportsEventId] [int] NOT NULL FOREIGN KEY REFERENCES SportsEvents(Id)
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO


SET ANSI_NULLS OFF

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Games](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](55) NOT NULL,
	[HomeTeam] [int] NULL,
	[AwayTeam] [int] NULL,
	[StartTime] [datetime] NOT NULL,
	[GameType] [int] NOT NULL,
	[SportsEventId] [int] NOT NULL,
	[GroupId] [int] NULL FOREIGN KEY REFERENCES Groups(Id),
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS OFF

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PlayoffGameDetails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NextPlayoffGame] [int] NULL,
	[NextPlayoffGameRunnerUp] [int] NULL,
	[IsHomeTeamInRunnerUpGame] [int] NULL,
	[IsHomeTeamNextGame] [int] NULL,
	[HomeTeamDisplayName] varchar (55) NULL,
	[AwayTeamDisplayName] varchar (55) NULL,
	[GameId] [int] NOT NULL FOREIGN KEY REFERENCES Games(Id)
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Teams](
 [Id] [int] IDENTITY(1,1) NOT NULL,
 [Name] [varchar](55) NOT NULL,
 [Flag] [varchar](255) NULL,
 [SportsEventId] int NOT NULL,
 [GroupId] [int] NULL FOREIGN KEY REFERENCES Groups(Id)
PRIMARY KEY CLUSTERED 
(
 [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TeamGames](
	[TeamId] int NOT NULL FOREIGN KEY REFERENCES Teams(Id),
	[IsHomeTeam] bit NOT NULL,
	[GameId] int NOT NULL FOREIGN KEY REFERENCES Games(Id),
	[Id] [int] IDENTITY(1,1) NOT NULL,
 PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[UserBets](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SportsEventId] int NOT NULL FOREIGN KEY REFERENCES SportsEvents(Id),
	[UserId] [varchar](255) NOT NULL, 
	[IsResultBet] bit NOT NULL
 CONSTRAINT [PrimaryKey_1055e9b1-54a2-4452-b154-79f38c806047] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO
SET ANSI_NULLS OFF

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Bets](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HomeGoals] [int] NOT NULL,
	[AwayGoals] [int] NOT NULL,
	[Result] [int] NOT NULL,
	[UserBetId] int NULL FOREIGN KEY REFERENCES UserBets(Id),
	[GameId] int NOT NULL FOREIGN KEY REFERENCES Games(Id)
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS OFF

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PlayoffBets](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Result] [int] NULL,
	[HomeTeam] [int] NOT NULL,
	[AwayTeam] [int] NOT NULL,
	[GameType] [int] NOT NULL,
	[HomeGoals] [int] NULL,
	[AwayGoals] [int] NULL,
	[UserBetId] int NULL FOREIGN KEY REFERENCES UserBets(Id),
	[GameId] int NOT NULL FOREIGN KEY REFERENCES Games(Id)
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Results](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserBetId] [int] NOT NULL,
	[SportsEventId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [dbo].[UserScores](
	[Score] [int] NOT NULL,
	[PlayoffScore] [int] NULL,
	[SportsEventId] int NOT NULL FOREIGN KEY REFERENCES SportsEvents(Id),
	[UserId] [varchar](255) NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PrimaryKey_4929abcf-b3fd-4f3f-85bc-72b7c7b481c4] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [dbo].[ScoreBasis](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GameType] [int] NOT NULL,
	[SportsEventId] int NOT NULL,
	[GradeOfMatchType] int NOT NULL,
	[Points] int NOT NULL,
	[IsRunnerUp] bit NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [dbo].[Leagues](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] varchar(255) NOT NULL,
	[SportsEventId] int NOT NULL,
	[Guid] varchar(255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LeagueUsers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LeagueId] int NOT NULL,
	[UserId] varchar(255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO
