//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footbet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Footbet.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///	&quot;Id&quot;: 1,
        ///	&quot;StartTime&quot;: &quot;\/Date(1402603200000)\/&quot;,
        ///	&quot;HomeGoals&quot;: null,
        ///	&quot;AwayGoals&quot;: null,
        ///	&quot;Result&quot;: null,
        ///	&quot;GameType&quot;: 1,
        ///	&quot;SportsEventId&quot;: 1,
        ///	&quot;Name&quot;: &quot;Kamp 1&quot;,
        ///	&quot;HomeTeam&quot;: 1,
        ///	&quot;AwayTeam&quot;: 2,
        ///	&quot;PlayoffGameDetails&quot;: []
        ///},
        ///{
        ///	&quot;Id&quot;: 2,
        ///	&quot;StartTime&quot;: &quot;\/Date(1402675200000)\/&quot;,
        ///	&quot;HomeGoals&quot;: null,
        ///	&quot;AwayGoals&quot;: null,
        ///	&quot;Result&quot;: null,
        ///	&quot;GameType&quot;: 1,
        ///	&quot;SportsEventId&quot;: 1,
        ///	&quot;Name&quot;: &quot;Kamp 2&quot;,
        ///	&quot;HomeTeam&quot;: 3,
        ///	&quot;AwayTeam&quot;: 4,
        ///	&quot;PlayoffGameDetails&quot;: []
        ///},
        ///{
        ///	&quot;Id&quot;: 3,
        ///	&quot;StartTime&quot;: &quot;\/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string brasil_games {
            get {
                return ResourceManager.GetString("brasil_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///	&quot;Id&quot;: 1,
        ///	&quot;Name&quot;: &quot;Brasil&quot;,
        ///	&quot;Flag&quot;: &quot;flag-br&quot;,
        ///	&quot;GroupId&quot;: 1,
        ///	&quot;SportsEventId&quot;: 1
        ///},
        ///{
        ///	&quot;Id&quot;: 2,
        ///	&quot;Name&quot;: &quot;Kroatia&quot;,
        ///	&quot;Flag&quot;: &quot;flag-hr&quot;,
        ///	&quot;GroupId&quot;: 1,
        ///	&quot;SportsEventId&quot;: 1
        ///},
        ///{
        ///	&quot;Id&quot;: 3,
        ///	&quot;Name&quot;: &quot;Mexico&quot;,
        ///	&quot;Flag&quot;: &quot;flag-mx&quot;,
        ///	&quot;GroupId&quot;: 1,
        ///	&quot;SportsEventId&quot;: 1
        ///},
        ///{
        ///	&quot;Id&quot;: 4,
        ///	&quot;Name&quot;: &quot;Kamerun&quot;,
        ///	&quot;Flag&quot;: &quot;flag-cm&quot;,
        ///	&quot;GroupId&quot;: 1,
        ///	&quot;SportsEventId&quot;: 1
        ///},
        ///{
        ///	&quot;Id&quot;: 5,
        ///	&quot;Name&quot;: &quot;Spania&quot;,
        ///	&quot;Flag&quot;: &quot;flag-es&quot;,
        ///	&quot;GroupId&quot;: 2,
        ///	&quot;SportsEventId&quot;: 1
        ///},
        ///{
        ///	&quot;Id&quot;: 6,
        ///	&quot;Name&quot;: &quot;Neder [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string brasil_teams {
            get {
                return ResourceManager.GetString("brasil_teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Groups&quot;: [{
        ///		&quot;Id&quot;: 1,
        ///		&quot;Name&quot;: &quot;Gruppe A&quot;,
        ///		&quot;WinnerTeamCode&quot;: null,
        ///		&quot;RunnerUpTeamCode&quot;: null,
        ///		&quot;WinnerGameCode&quot;: &quot;49&quot;,
        ///		&quot;RunnerUpGameCode&quot;: &quot;51&quot;,
        ///		&quot;SportsEventId&quot;: 1,
        ///		&quot;Teams&quot;: [{
        ///			&quot;Id&quot;: 1,
        ///			&quot;Name&quot;: &quot;Brasil&quot;,
        ///			&quot;Flag&quot;: &quot;flag-br&quot;,
        ///			&quot;GroupId&quot;: 1
        ///		},
        ///		{
        ///			&quot;Id&quot;: 2,
        ///			&quot;Name&quot;: &quot;Kroatia&quot;,
        ///			&quot;Flag&quot;: &quot;flag-hr&quot;,
        ///			&quot;GroupId&quot;: 1
        ///		},
        ///		{
        ///			&quot;Id&quot;: 3,
        ///			&quot;Name&quot;: &quot;Mexico&quot;,
        ///			&quot;Flag&quot;: &quot;flag-mx&quot;,
        ///			&quot;GroupId&quot;: 1
        ///		},
        ///		{
        ///			&quot;Id&quot;: 4,
        ///			&quot;Name&quot;: &quot;Kamerun&quot;,
        ///			&quot;Flag&quot;: &quot;fl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string brasil_wrong_old {
            get {
                return ResourceManager.GetString("brasil_wrong_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;groups&quot;:[{&quot;id&quot;:1,&quot;name&quot;:&quot;Gruppe A&quot;,&quot;winnerTeamCode&quot;:null,&quot;runnerUpTeamCode&quot;:null,&quot;winnerGameCode&quot;:&quot;50&quot;,&quot;runnerUpGameCode&quot;:&quot;51&quot;,&quot;sportsEventId&quot;:1,&quot;teams&quot;:[{&quot;id&quot;:1,&quot;name&quot;:&quot;Russland&quot;,&quot;flag&quot;:&quot;flag-ru&quot;,&quot;groupId&quot;:1,&quot;sportsEventId&quot;:1},{&quot;id&quot;:2,&quot;name&quot;:&quot;Saudi-Arabia&quot;,&quot;flag&quot;:&quot;flag-sa&quot;,&quot;groupId&quot;:1,&quot;sportsEventId&quot;:1},{&quot;id&quot;:3,&quot;name&quot;:&quot;Egypt&quot;,&quot;flag&quot;:&quot;flag-eg&quot;,&quot;groupId&quot;:1,&quot;sportsEventId&quot;:1},{&quot;id&quot;:4,&quot;name&quot;:&quot;Uruguay&quot;,&quot;flag&quot;:&quot;flag-uy&quot;,&quot;groupId&quot;:1,&quot;sportsEventId&quot;:1}],&quot;games&quot;:[{&quot;id&quot;:1,&quot;startTime&quot;:&quot;14.06.2018 17:00&quot;,&quot;homeGoals&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gameSetupRussia {
            get {
                return ResourceManager.GetString("gameSetupRussia", resourceCulture);
            }
        }
    }
}
