//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footbet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Footbet.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;bets&quot;: [],
        ///    &quot;playoffGameDetails&quot;: [],
        ///    &quot;id&quot;: 1,
        ///    &quot;name&quot;: &quot;Kamp 1&quot;,
        ///    &quot;homeTeam&quot;: 1,
        ///    &quot;awayTeam&quot;: 2,
        ///    &quot;startTime&quot;: &quot;2018-06-14T17:00:00&quot;,
        ///    &quot;gameType&quot;: 1,
        ///    &quot;sportsEventId&quot;: 1,
        ///    &quot;groupId&quot;: 1
        ///  },
        ///  {
        ///    &quot;bets&quot;: [],
        ///    &quot;playoffGameDetails&quot;: [],
        ///    &quot;id&quot;: 2,
        ///    &quot;name&quot;: &quot;Kamp 2&quot;,
        ///    &quot;homeTeam&quot;: 3,
        ///    &quot;awayTeam&quot;: 4,
        ///    &quot;startTime&quot;: &quot;2018-06-15T14:00:00&quot;,
        ///    &quot;gameType&quot;: 1,
        ///    &quot;sportsEventId&quot;: 1,
        ///    &quot;groupId&quot;: 1
        ///  },
        ///  {
        ///    &quot;bets&quot;: [],
        ///    &quot;pl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string games {
            get {
                return ResourceManager.GetString("games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;groups&quot;: [
        ///    {
        ///      &quot;id&quot;: 1,
        ///      &quot;name&quot;: &quot;Gruppe A&quot;,
        ///      &quot;winnerGameId&quot;: 50,
        ///      &quot;runnerUpGameId&quot;: 51,
        ///      &quot;sportsEventId&quot;: 1,
        ///      &quot;teams&quot;: [
        ///        {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;Russland&quot;,
        ///          &quot;flag&quot;: &quot;flag-ru&quot;,
        ///          &quot;groupId&quot;: 1,
        ///          &quot;sportsEventId&quot;: 1
        ///        },
        ///        {
        ///          &quot;id&quot;: 2,
        ///          &quot;name&quot;: &quot;Saudi-Arabia&quot;,
        ///          &quot;flag&quot;: &quot;flag-sa&quot;,
        ///          &quot;groupId&quot;: 1,
        ///          &quot;sportsEventId&quot;: 1
        ///        },
        ///        {
        ///          &quot;id&quot;: 3,
        ///          &quot;name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gameSetupRussia {
            get {
                return ResourceManager.GetString("gameSetupRussia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;team&quot;:&quot;Egypt&quot;,&quot;players&quot;:[{&quot;name&quot;:&quot;Essam El-Hadary&quot;},{&quot;name&quot;:&quot;Sherif Ekramy&quot;},{&quot;name&quot;:&quot;Mohamed Awad&quot;},{&quot;name&quot;:&quot;Mohamed El-Shenawy&quot;},{&quot;name&quot;:&quot;Ahmed Fathy&quot;},{&quot;name&quot;:&quot;Ahmed Elmohamady&quot;},{&quot;name&quot;:&quot;Mohamed Abdel-Shafy&quot;},{&quot;name&quot;:&quot;Ahmed Hegazi&quot;},{&quot;name&quot;:&quot;Omar Gaber&quot;},{&quot;name&quot;:&quot;Ali Gabr&quot;},{&quot;name&quot;:&quot;Saad Samir&quot;},{&quot;name&quot;:&quot;Karim Hafez&quot;},{&quot;name&quot;:&quot;Ayman Ashraf&quot;},{&quot;name&quot;:&quot;Amro Tarek&quot;},{&quot;name&quot;:&quot;Mahmoud Hamdy&quot;},{&quot;name&quot;:&quot;Mohamed Elneny&quot;},{&quot;name&quot;:&quot;Abdallah Said&quot;},{&quot;name&quot;:&quot;Shikabala&quot;},{&quot;name&quot;:&quot;Trézéguet&quot;},{&quot;name&quot;:&quot;Ramadan Sobh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///	&quot;id&quot;: 1,
        ///	&quot;name&quot;: &quot;Russland&quot;,
        ///	&quot;flag&quot;: &quot;flag-ru&quot;,
        ///	&quot;groupId&quot;: 1,
        ///	&quot;sportsEventId&quot;: 1,
        ///	&quot;englishName&quot;: &quot;Russia&quot;
        ///},
        ///{
        ///	&quot;id&quot;: 2,
        ///	&quot;name&quot;: &quot;Saudi-Arabia&quot;,
        ///	&quot;flag&quot;: &quot;flag-sa&quot;,
        ///	&quot;groupId&quot;: 1,
        ///	&quot;sportsEventId&quot;: 1,
        ///	&quot;englishName&quot;: &quot;Saudi Arabia&quot;
        ///},
        ///{
        ///	&quot;id&quot;: 3,
        ///	&quot;name&quot;: &quot;Egypt&quot;,
        ///	&quot;flag&quot;: &quot;flag-eg&quot;,
        ///	&quot;groupId&quot;: 1,
        ///	&quot;sportsEventId&quot;: 1,
        ///	&quot;englishName&quot;: &quot;Egypt&quot;
        ///},
        ///{
        ///	&quot;id&quot;: 4,
        ///	&quot;name&quot;: &quot;Uruguay&quot;,
        ///	&quot;flag&quot;: &quot;flag-uy&quot;,
        ///	&quot;groupId&quot;: 1,
        ///	&quot;sportsEventId&quot;: 1,
        ///	&quot;englishName&quot;: &quot;Uruguay&quot;
        ///},
        ///{
        ///	&quot;id&quot;: 5,
        ///	&quot;name&quot;: &quot;Portugal&quot;,
        ///	&quot;fl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string teams {
            get {
                return ResourceManager.GetString("teams", resourceCulture);
            }
        }
    }
}
